### ISSUE TITLE
TODO: Add Raspberry Pi support

### ISSUE THREAD

**Issue by xarunoba** [Xarunoba/uplink.js#2]
- [ ] add Raspberry Pi support
- [ ] attempt to test Raspberry Pi support (Volunteers appreciated)
- [ ] release working Raspberry Pi support
