### ISSUE TITLE
TODO: Rewrite update.js as a proper custom command

### ISSUE THREAD

**Issue by xarunoba** [Xarunoba/uplink.js#4]
- [ ] rewrite `update.js` as a proper custom command
- [ ] test the rewrite
- [ ] release working release package
